version: '3.8'

services:
  app:
    image: justinkozlowski/projects:portfolio
    environment:
      - VIRTUAL_HOST=www.justinkozlowski.me
      - LETSENCRYPT_HOST=www.justinkozlowski.me
      - LETSENCRYPT_EMAIL=contact@justinkozlowski.me
    restart: always
    ports:
      - "8000:8000"
    network_mode: bridge
